title: Nick DeSteffen's Blog
author: Nick DeSteffen

description: >
  Nick DeSteffen's blog and personal website

baseurl: "/"
url: "https://www.nickdesteffen.com"

github_username:  nick-desteffen
twitter_username: NickDesteffen
linkedin_username: nickdesteffen
stackoverflow_username: nick-desteffen

collections:
  - setup

minimaless:
  date_format: "%b %-d, %Y"
preview_posts: true
permalink: /blog/:title
paginate: 5
paginate_path: "/page:num/"

header_pages:
  - about.md
  - contact.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate

markdown: kramdown
remote_theme: brettinternet/minimaless

include:
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - tmp
